baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "OliG theme"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Olivier Gallou"
        tagline = "Chef de projet"
        location = "Rennes"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "#"
            title = "GitHub"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "A propos de moi"
        icon = "fas fa-user"
        description = "This is a demo of the `aafu` theme. It has `light`, `dark`, `ocean`, and `pinkish` themes."

    # Experience section
    [params.experience]
        title = "Expériences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Chef de produit Vie/Banque"
            dates = "Mai 2020 - Décembre 2020"
            company = "Groupama Loire Bretagne"
            details = "· Préparation et mise en œuvre des actions commerciales. -Coordination et suivi l’activité du secteur de l’Épargne/Retraite -Analyse et suivi de la situation de l’entreprise par rapport à ses marchés, ses clientèles et ses produits -Coordination des partenariats avec GGVie et Orange Bank"
        [[params.experience.list]]
            position = "Job Title"
            dates = "2018 - 2019"
            url = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Formation"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_url = "#"
        [[params.education.list]]
            degree = "M.S. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_url = "#"
        [[params.education.list]]
            degree = "B.S. in Subject"
            college = "University of State-City"
            dates = "2004 - 2009"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Loisirs"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cuisine"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"